# -*- coding: utf-8 -*-
"""Análise de Sentimento em Tempo Real.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E40nynQ-RCwRbsoB1NYUVRi83yu59poB

# **Coleta de Dados (Reddit & News)!**
## O Reddit é uma mina de ouro para opiniões sobre IA (subreddits como r/artificialintelligence ou r/technology).
"""

# Instalação das Bibliotecas
# O vaderSentiment é o padrão ouro para redes sociais.

!pip install feedparser
!pip install vaderSentiment wordcloud matplotlib pandas

"""## Projeto (Análise de IA)"""

import pandas as pd
import feedparser
import matplotlib.pyplot as plt
import seaborn as sns
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from wordcloud import WordCloud, STOPWORDS
from urllib.parse import quote

# Configuração visual
sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 100

def coletar_dados_premium(termo):
    print(f"🚀 Iniciando extração de dados para: {termo}")
    termo_codificado = quote(termo)
    url = f"https://news.google.com/rss/search?q={termo_codificado}&hl=pt-BR&gl=BR&ceid=BR:pt-419"
    feed = feedparser.parse(url)

    dados = []
    for entry in feed.entries[:100]: # Aumentamos para 100 para mais volume
        # Extrai o veículo (ex: "Título da Notícia - G1" -> "G1")
        fonte = entry.title.split(' - ')[-1] if ' - ' in entry.title else "Outros"
        titulo_limpo = entry.title.split(' - ')[0]

        dados.append({
            'titulo': titulo_limpo,
            'veiculo': fonte,
            'data': entry.published
        })
    return pd.DataFrame(dados)

# 1. Execução
df = coletar_dados_premium("Inteligência Artificial")

# 2. Análise de Sentimento
analyzer = SentimentIntensityAnalyzer()
df['score'] = df['titulo'].apply(lambda x: analyzer.polarity_scores(x)['compound'])
df['sentimento'] = df['score'].apply(lambda s: 'Positivo' if s >= 0.05 else ('Negativo' if s <= -0.05 else 'Neutro'))

# 3. DASHBOARD VISUAL
fig = plt.figure(figsize=(20, 12))
grid = plt.GridSpec(2, 2, wspace=0.3, hspace=0.3)

# --- Subplot 1: Distribuição de Sentimentos (Donut Chart) ---
ax1 = fig.add_subplot(grid[0, 0])
cores = ['#66b3ff','#99ff99','#ff9999']
contagem = df['sentimento'].value_counts()
ax1.pie(contagem, labels=contagem.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"), pctdistance=0.85)
center_circle = plt.Circle((0,0),0.70,fc='white')
ax1.add_artist(center_circle)
ax1.set_title("Market Share de Sentimento", fontsize=15, fontweight='bold')

# --- Subplot 2: Top Veículos de Comunicação ---
ax2 = fig.add_subplot(grid[0, 1])
top_veiculos = df['veiculo'].value_counts().head(10)
sns.barplot(x=top_veiculos.values, y=top_veiculos.index, palette="viridis", ax=ax2)
ax2.set_title("Top 10 Fontes de Notícias", fontsize=15, fontweight='bold')

# --- Subplot 3: Nuvem de Palavras (Customizada) ---
ax3 = fig.add_subplot(grid[1, :])
stop_words_pt = set(STOPWORDS)
stop_words_pt.update(["IA", "inteligência", "artificial", "sobre", "mais", "pode", "diz", "novo", "nova"]) # Filtra o óbvio

# Adicione mais palavras irrelevantes para limpar o gráfico
stop_words_pt = set(STOPWORDS)
stop_words_pt.update([
    "de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "é", "com",
    "não", "uma", "os", "no", "se", "na", "por", "mais", "as", "dos", "das",
    "como", "mas", "foi", "ao", "pelo", "pela", "sobre", "ia", "inteligência", "artificial"
])

wordcloud = WordCloud(
    width=1600, height=800,
    background_color='black',
    stopwords=stop_words_pt, # Aqui ele aplica o filtro
    colormap='icefire',
    max_words=80
).generate(" ".join(df['titulo'].str.lower())) # .lower() ajuda a padronizar

ax3.imshow(wordcloud, interpolation='bilinear')
ax3.axis('off')
ax3.set_title("Termos em Destaque no Ecossistema de IA", fontsize=15, fontweight='bold')

plt.suptitle(f"Analytics: Percepção Midiática sobre IA", fontsize=22, fontweight='bold', y=0.98)
plt.show()